base.url=http://localhost:5252
browser=chrome
headless=false

admin.username=admin
admin.password=123123

customer1.username=truonghuynhthaon63@gmail.com
customer1.password=123123

customer2.username=khanhduy2911@gmail.com
customer2.password=123123